[tool.poetry.dependencies]
python = ">=3.10,<3.11"
absl-py = "2.1.0"
aiohappyeyeballs = "2.3.5"
aiohttp = "3.10.3"
aiosignal = "1.3.1"
annotated-types = "0.7.0"
anthropic = "0.34.0"
anyio = "4.4.0"
async-timeout = "4.0.3"
attrs = "24.2.0"
blis = "0.7.11"
bottle = "0.12.25"
cachetools = "5.4.0"
setuptools = "^60.8.0"
catalogue = "2.0.10"
cattrs = "22.2.0"
certifi = "2024.7.4"
charset-normalizer = "3.3.2"
click = "8.1.7"
cloudpathlib = "0.18.1"
confection = "0.1.5"
contourpy = "1.2.1"
cycler = "0.12.1"
cymem = "2.0.8"
dacite = "1.8.1"
datasets = "2.21.0"
dill = "0.3.8"
distro = "1.9.0"
docstring_parser = "0.16"
exceptiongroup = "1.2.2"
filelock = "3.15.4"
fonttools = "4.53.1"
frozenlist = "1.4.1"
fsspec = "2024.6.1"
google-api-core = "2.19.1"
google-api-python-client = "2.141.0"
google-auth = "2.33.0"
google-auth-httplib2 = "0.2.0"
google-cloud-aiplatform = "1.60.0"
google-cloud-bigquery = "3.25.0"
google-cloud-core = "2.4.1"
google-cloud-resource-manager = "1.12.5"
google-cloud-storage = "2.18.2"
google-crc32c = "1.5.0"
google-resumable-media = "2.7.2"
googleapis-common-protos = "1.63.2"
grpc-google-iam-v1 = "0.13.1"
grpcio = "1.65.4"
grpcio-status = "1.62.3"
h11 = "0.14.0"
httpcore = "1.0.5"
httplib2 = "0.22.0"
httpx = "0.27.0"
huggingface-hub = "0.24.5"
idna = "3.7"
importlib-resources = "5.13.0"
Jinja2 = "3.1.4"
jiter = "0.5.0"
joblib = "1.4.2"
kiwisolver = "1.4.5"
langcodes = "3.4.0"
language_data = "1.2.0"
Mako = "1.3.5"
marisa-trie = "1.2.0"
markdown-it-py = "3.0.0"
MarkupSafe = "2.1.5"
matplotlib = "3.9.2"
mdurl = "0.1.2"
mpmath = "1.3.0"
multidict = "6.0.5"
multiprocess = "0.70.16"
murmurhash = "1.0.10"
networkx = "3.3"
nltk = "3.8.1"
numpy = "1.26.4"
nvidia-cublas-cu12 = "12.1.3.1"
nvidia-cuda-cupti-cu12 = "12.1.105"
nvidia-cuda-nvrtc-cu12 = "12.1.105"
nvidia-cuda-runtime-cu12 = "12.1.105"
nvidia-cudnn-cu12 = "9.1.0.70"
nvidia-cufft-cu12 = "11.0.2.54"
nvidia-curand-cu12 = "10.3.2.106"
nvidia-cusolver-cu12 = "11.4.5.107"
nvidia-cusparse-cu12 = "12.1.0.106"
nvidia-nccl-cu12 = "2.20.5"
nvidia-nvjitlink-cu12 = "12.6.20"
nvidia-nvtx-cu12 = "12.1.105"
openai = "1.40.6"
packaging = "24.1"
pandas = "2.2.2"
parameterized = "0.9.0"
pillow = "10.4.0"
preshed = "3.0.9"
proto-plus = "1.24.0"
protobuf = "4.25.4"
pyarrow = "17.0.0"
pyarrow-hotfix = "0.6"
pyasn1 = "0.6.0"
pyasn1_modules = "0.4.0"
pydantic = "2.8.2"
pydantic_core = "2.20.1"
pyext = "^0.6"
Pygments = "2.18.0"
pyhocon = "0.3.61"
pyparsing = "3.1.2"
python-dateutil = "2.9.0.post0"
pytz = "2024.1"
PyYAML = "6.0.2"
regex = "2024.7.24"
requests = "2.32.3"
retrying = "1.3.4"
rich = "13.7.1"
rouge_score = "0.1.2"
rsa = "4.9"
safetensors = "0.4.4"
scikit-learn = "1.5.1"
scipy = "1.14.0"
shapely = "2.0.5"
shellingham = "1.5.4"
six = "1.16.0"
smart-open = "7.0.4"
sniffio = "1.3.1"
spacy = "3.7.5"
spacy-legacy = "3.0.12"
spacy-loggers = "1.0.5"
sqlitedict = "1.7.0"
srsly = "2.4.8"
sympy = "1.13.2"
thinc = "8.2.5"
threadpoolctl = "3.5.0"
tiktoken = "0.7.0"
tensorflow = "^2.17.0"
tokenizers = "0.19.1"
torch = "2.4.0"
torchvision = "0.19.0"
tqdm = "4.66.5"
transformers = "4.44.0"
accelerate = "^0.33.0"
peft = "^0.9.0"
triton = "3.0.0"
typer = "0.12.3"
typing_extensions = "4.12.2"
tzdata = "2024.1"
uncertainty-calibration = "0.1.4"
uritemplate = "4.1.1"
urllib3 = "2.2.2"
vertexai = "1.60.0"
wasabi = "1.1.3"
weasel = "0.4.1"
wrapt = "1.16.0"
xxhash = "3.4.1"
yarl = "1.9.4"
evaluate = "^0.4.2"
zstandard = "0.18.0"
MLAgentBench = { git = "https://github.com/<Anonymous>/MLAgentBench.git", rev = "5d71205cc20a8e95d43aa7cb7120e89ca3323e31" }
dm-clrs = { git = "https://github.com/google-deepmind/clrs.git", rev = "3ba3f2d5f7e832d8076b5bb9c8c05d3dfc4bf18e" }
crfm-helm = { git = "https://github.com/<Anonymous>/helm.git", rev = "bcce29d26219f28b4ce8f61f4bee1939887c2ee2"}
